#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
COPY webdrivers /webdrivers
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build /home/app/target/demo-1.0-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8282
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]
